baseURL = "https://codingforbeer.github.io/"
languageCode = "en-us"
title = "Coding for Beer ğŸ»"

theme = "vitae"

pygmentsstyle = "tango"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
